### Messing around with Tensorflow

Tensorflow has the keras API which is helpful for creating neural network models and stuff. I want to make sure that I understand these basic parts and play around with the inputs and outputs. The units that I'm going to play with are: 
* `Dense` layers
* `LSTM` layers

#### `Dense` layers

Dense layers are very easy to understand and are on the most popular types of layers. They are your usual linear layers which do $w*x + b$ on all of the inputs that come into it. 

In [1]:
import tensorflow as tf
import yfinance as yf

from tensorflow.keras.layers import Dense, LSTM, LSTMCell, Conv1D, Conv2D

In [9]:
layer = Dense(10, activation = 'relu')

# Create a random input tensor that is 10 by 10
input = tf.random.uniform(shape = (10, 10))

In [11]:
# Notice that the layer is not built yet. Not until we call it on some input
layer.built # Prints false

False

In [12]:
output = layer(input)

In [13]:
output.shape

TensorShape([10, 10])

In [14]:
output

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1.1320157 , 0.        , 0.        , 0.29086697, 1.2082905 ,
        0.        , 0.44645086, 0.        , 0.24970917, 0.3864699 ],
       [0.9984772 , 0.        , 0.        , 0.        , 0.12440576,
        0.        , 0.6753725 , 0.45127672, 0.        , 0.17300612],
       [1.1751791 , 0.04724599, 0.09362239, 0.5716742 , 0.5330423 ,
        0.        , 0.04949938, 0.        , 0.        , 0.5707932 ],
       [0.43370414, 0.        , 0.        , 0.40394986, 0.5041968 ,
        0.0671923 , 0.9884647 , 0.31064576, 0.        , 0.13070509],
       [1.3167008 , 0.        , 0.        , 0.00290375, 0.84109294,
        0.        , 0.62947834, 0.12499978, 0.        , 1.1681409 ],
       [0.67977184, 0.        , 0.28024074, 0.27838978, 0.83167756,
        0.        , 0.24468848, 0.20759429, 0.        , 0.10520376],
       [1.0787448 , 0.        , 0.        , 0.26105654, 0.9413522 ,
        0.        , 0.10901481, 0.10013229, 0.        , 0.30

In [15]:
layer.built

True

In [16]:

layer.weights

[<tf.Variable 'dense_2/kernel:0' shape=(10, 10) dtype=float32, numpy=
 array([[ 0.386284  , -0.23301843,  0.49429798,  0.27465594,  0.45845222,
          0.09771138, -0.22598055, -0.18124673,  0.15364385, -0.09423462],
        [ 0.17197907,  0.14548135,  0.18248063, -0.4598593 ,  0.32750523,
         -0.12459719,  0.38275355, -0.03462678, -0.17705736,  0.5332242 ],
        [ 0.1999327 ,  0.539112  , -0.35419607, -0.09280065, -0.47800243,
         -0.30022907, -0.485267  ,  0.00286937, -0.19410631, -0.24564034],
        [ 0.34256923, -0.1721431 , -0.31837833, -0.1605339 ,  0.5237516 ,
          0.1406703 , -0.39065605, -0.39777642,  0.2576558 ,  0.42212665],
        [ 0.07935238, -0.5253116 , -0.54293966, -0.11358583,  0.28003573,
          0.37683392,  0.261716  ,  0.1911779 , -0.4986688 ,  0.19135797],
        [ 0.29425055,  0.13603586,  0.41012347,  0.3874001 ,  0.45750415,
         -0.30228895, -0.17820704,  0.15014696,  0.09007204,  0.06727791],
        [-0.03867066,  0.3789395 ,  

#### `LSTM` layers

In [96]:
rnn_layer = LSTM(units = 10)
rnn_layer_return_sequences = LSTM(units = 10, return_sequences=True, return_state=True)

In [97]:
rnn_layer.built

False

In [98]:
btc_data = yf.download(tickers='BTC-USD', progress=False)
close_series = btc_data['Adj Close']

In [99]:
series = close_series.iloc[:32]
series = series.values.reshape(-1, 1)

# Creating the series to be good for an RNN input
rnn_input_series = tf.constant([series])

In [100]:
rnn_output = rnn_layer(rnn_input_series)

In [101]:
rnn_output

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[-4.8842553e-34, -7.6700437e-01,  7.6159418e-01,  0.0000000e+00,
         2.1719061e-01,  1.7979165e-08, -1.5139581e-20,  0.0000000e+00,
        -1.0966111e-14,  0.0000000e+00]], dtype=float32)>

In [102]:
rnn_output_with_sequences = rnn_layer_return_sequences(rnn_input_series)

In [103]:
rnn_output_with_sequences

[<tf.Tensor: shape=(1, 32, 10), dtype=float32, numpy=
 array([[[-5.25623332e-36,  0.00000000e+00,  5.09884310e-30,
           0.00000000e+00,  6.27817350e-23,  9.51131264e-14,
           0.00000000e+00, -5.65578530e-12, -2.33564693e-02,
          -7.60448635e-01],
         [-1.88842561e-33,  0.00000000e+00,  1.06048848e-27,
           0.00000000e+00,  3.05375776e-21,  6.80876037e-13,
           0.00000000e+00, -4.40546176e-11, -5.58022670e-02,
          -9.63580430e-01],
         [-3.70867151e-31,  0.00000000e+00,  1.08465946e-25,
           0.00000000e+00,  8.40428104e-20,  4.49706591e-12,
           0.00000000e+00, -2.51522358e-10, -9.17037204e-02,
          -9.94941711e-01],
         [-4.01285042e-31,  0.00000000e+00,  2.22903187e-26,
           0.00000000e+00,  1.73339332e-20,  1.75677214e-12,
           0.00000000e+00, -3.44325374e-10, -1.09473012e-01,
          -9.99308169e-01],
         [-5.82999213e-31,  0.00000000e+00,  1.14978794e-25,
           0.00000000e+00,  5.28393443e-2